apiVersion: v1
kind: Service
metadata:
  name: simple-api-preview
  labels:
    app: simple-api
spec:
  selector:
    app: simple-api
 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  # type: LoadBalancer