apiVersion: v1
kind: Service
metadata:
  name: simple-fe-preview
  labels:
    app: simple-fe
spec:
  selector:
    app: simple-fe
 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer